package com.tenement.model;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.name
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.code
     *
     * @return the value of country.code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.code
     *
     * @param code the value for country.code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.name
     *
     * @return the value of country.name
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.name
     *
     * @param name the value for country.name
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}