package com.tenement.model;

public class County {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.id
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.name
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.url
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.city_code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    private String cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.id
     *
     * @return the value of county.id
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.id
     *
     * @param id the value for county.id
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.code
     *
     * @return the value of county.code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.code
     *
     * @param code the value for county.code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.name
     *
     * @return the value of county.name
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.name
     *
     * @param name the value for county.name
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.url
     *
     * @return the value of county.url
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.url
     *
     * @param url the value for county.url
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.city_code
     *
     * @return the value of county.city_code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.city_code
     *
     * @param cityCode the value for county.city_code
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }
}