package com.tenement.model;

public class UserHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_house.id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_house.user_id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_house.house_id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    private Long houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_house.remark
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_house.description
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_house.id
     *
     * @return the value of user_house.id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_house.id
     *
     * @param id the value for user_house.id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_house.user_id
     *
     * @return the value of user_house.user_id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_house.user_id
     *
     * @param userId the value for user_house.user_id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_house.house_id
     *
     * @return the value of user_house.house_id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public Long getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_house.house_id
     *
     * @param houseId the value for user_house.house_id
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public void setHouseId(Long houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_house.remark
     *
     * @return the value of user_house.remark
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_house.remark
     *
     * @param remark the value for user_house.remark
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_house.description
     *
     * @return the value of user_house.description
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_house.description
     *
     * @param description the value for user_house.description
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}