package com.tenement.mapper;

import com.tenement.model.County;
import com.tenement.model.CountyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int countByExample(CountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int deleteByExample(CountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int insert(County record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int insertSelective(County record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    List<County> selectByExample(CountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    County selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") County record, @Param("example") CountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int updateByExample(@Param("record") County record, @Param("example") CountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int updateByPrimaryKeySelective(County record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbggenerated Wed Apr 27 15:07:33 CST 2016
     */
    int updateByPrimaryKey(County record);
}