package com.tenement.mapper;

import com.tenement.model.Landlord;
import com.tenement.model.LandlordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LandlordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int countByExample(LandlordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int deleteByExample(LandlordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    int insert(Landlord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int insertSelective(Landlord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    List<Landlord> selectByExample(LandlordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    Landlord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") Landlord record, @Param("example") LandlordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int updateByExample(@Param("record") Landlord record, @Param("example") LandlordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int updateByPrimaryKeySelective(Landlord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landlord
     *
     * @mbggenerated Tue May 03 15:55:21 CST 2016
     */
    int updateByPrimaryKey(Landlord record);
}