package com.tenement.mapper;

import com.tenement.model.Url;
import com.tenement.model.UrlExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int countByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int deleteByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int insertSelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    List<Url> selectByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    Url selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int updateByExample(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int updateByPrimaryKeySelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated Wed May 18 18:23:41 CST 2016
     */
    int updateByPrimaryKey(Url record);
}