package com.tenement.mapper;

import com.tenement.model.UserHouse;
import com.tenement.model.UserHouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int countByExample(UserHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int deleteByExample(UserHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int insert(UserHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int insertSelective(UserHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    List<UserHouse> selectByExample(UserHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    UserHouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserHouse record, @Param("example") UserHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int updateByExample(@Param("record") UserHouse record, @Param("example") UserHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int updateByPrimaryKeySelective(UserHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Thu May 05 13:49:27 CST 2016
     */
    int updateByPrimaryKey(UserHouse record);
}